# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lpdg-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://registry.hub.docker.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_99e2e03fdd4b41d6bf0a233f865f6d94 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c7623b35673f4073bfb76178fd6bf0d2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: registry.hub.docker.com/${{ secrets.AzureAppService_ContainerUsername_99e2e03fdd4b41d6bf0a233f865f6d94 }}/ashwamegh/lpdg-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'lpdg-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6922c523d89c4fc99f150a96a570fdc7 }}
        images: 'registry.hub.docker.com/${{ secrets.AzureAppService_ContainerUsername_99e2e03fdd4b41d6bf0a233f865f6d94 }}/ashwamegh/lpdg-server:${{ github.sha }}'